// Auto-generated by OpenLane
module decode_input(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[1:0] mode,
  input[5:0] select,
  input button_inc,
  input button_dec,
  input[4:0] done_inc,
  input[4:0] done_dec,
  output[5:0] inc,
  output[5:0] dec,
  output[5:0] en
);
endmodule
