/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module counter_all(clk, reset_n, day, month, year, hour, minute, second, day_num, hour_num, done_inc, done_dec, inc, dec, en);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  input clk;
  wire clk;
  output [4:0] day;
  wire [4:0] day;
  wire \day_inst.done_dec ;
  wire \day_inst.done_inc ;
  input [4:0] day_num;
  wire [4:0] day_num;
  input [5:0] dec;
  wire [5:0] dec;
  output [4:0] done_dec;
  wire [4:0] done_dec;
  output [4:0] done_inc;
  wire [4:0] done_inc;
  input [5:0] en;
  wire [5:0] en;
  output [4:0] hour;
  wire [4:0] hour;
  wire \hour_inst.done_dec ;
  wire \hour_inst.done_inc ;
  input [4:0] hour_num;
  wire [4:0] hour_num;
  input [5:0] inc;
  wire [5:0] inc;
  output [5:0] minute;
  wire [5:0] minute;
  wire \minute_inst.done_dec ;
  wire \minute_inst.done_inc ;
  output [3:0] month;
  wire [3:0] month;
  wire \month_inst.done_dec ;
  wire \month_inst.done_inc ;
  input reset_n;
  wire reset_n;
  output [5:0] second;
  wire [5:0] second;
  wire \second_inst.done_dec ;
  wire \second_inst.done_inc ;
  output [6:0] year;
  wire [6:0] year;
  sky130_fd_sc_hd__inv_2 _306_ (
    .A(inc[3]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_2 _307_ (
    .A(inc[2]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__inv_2 _308_ (
    .A(dec[2]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_2 _309_ (
    .A(hour[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_2 _310_ (
    .A(hour[3]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_2 _311_ (
    .A(hour_num[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _312_ (
    .A(day_num[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _313_ (
    .A(day_num[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_2 _314_ (
    .A(year[5]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _315_ (
    .A(year[3]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__or2_2 _316_ (
    .A(second[0]),
    .B(second[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__or3_2 _317_ (
    .A(second[3]),
    .B(second[2]),
    .C(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor3_2 _318_ (
    .A(second[4]),
    .B(second[5]),
    .C(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and2_2 _319_ (
    .A(dec[0]),
    .B(_045_),
    .X(\second_inst.done_dec )
  );
  sky130_fd_sc_hd__and3_2 _320_ (
    .A(second[3]),
    .B(second[4]),
    .C(second[5]),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2_2 _321_ (
    .A(second[0]),
    .B(second[1]),
    .X(_047_)
  );
  sky130_fd_sc_hd__and4b_2 _322_ (
    .A_N(second[2]),
    .B(_046_),
    .C(_047_),
    .D(inc[0]),
    .X(\second_inst.done_inc )
  );
  sky130_fd_sc_hd__nor2_2 _323_ (
    .A(minute[1]),
    .B(minute[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__or3_2 _324_ (
    .A(minute[1]),
    .B(minute[0]),
    .C(minute[2]),
    .X(_049_)
  );
  sky130_fd_sc_hd__or2_2 _325_ (
    .A(minute[3]),
    .B(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_2 _326_ (
    .A(minute[4]),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and2b_2 _327_ (
    .A_N(minute[5]),
    .B(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and2_2 _328_ (
    .A(dec[1]),
    .B(_052_),
    .X(\minute_inst.done_dec )
  );
  sky130_fd_sc_hd__and3_2 _329_ (
    .A(minute[3]),
    .B(minute[4]),
    .C(minute[5]),
    .X(_053_)
  );
  sky130_fd_sc_hd__and2_2 _330_ (
    .A(minute[1]),
    .B(minute[0]),
    .X(_054_)
  );
  sky130_fd_sc_hd__and4b_2 _331_ (
    .A_N(minute[2]),
    .B(_053_),
    .C(_054_),
    .D(inc[1]),
    .X(\minute_inst.done_inc )
  );
  sky130_fd_sc_hd__or2_2 _332_ (
    .A(hour[1]),
    .B(hour[0]),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2_2 _333_ (
    .A(hour[2]),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or4_2 _334_ (
    .A(hour[1]),
    .B(hour[0]),
    .C(hour[2]),
    .D(hour[3]),
    .X(_057_)
  );
  sky130_fd_sc_hd__or2_2 _335_ (
    .A(hour[4]),
    .B(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor2_2 _336_ (
    .A(_035_),
    .B(_058_),
    .Y(\hour_inst.done_dec )
  );
  sky130_fd_sc_hd__nand2b_2 _337_ (
    .A_N(hour[1]),
    .B(hour_num[1]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2b_2 _338_ (
    .A_N(hour_num[1]),
    .B(hour[1]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2b_2 _339_ (
    .A_N(hour[0]),
    .B(hour_num[0]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and3_2 _340_ (
    .A(_059_),
    .B(_060_),
    .C(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2b_2 _341_ (
    .A_N(hour_num[3]),
    .B(hour[3]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2b_2 _342_ (
    .A_N(hour_num[2]),
    .B(hour[2]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2b_2 _343_ (
    .A_N(hour[3]),
    .B(hour_num[3]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2b_2 _344_ (
    .A_N(hour[2]),
    .B(hour_num[2]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__and4_2 _345_ (
    .A(_063_),
    .B(_064_),
    .C(_065_),
    .D(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nand2b_2 _346_ (
    .A_N(hour[4]),
    .B(hour_num[4]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_2 _347_ (
    .A(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2b_2 _348_ (
    .A_N(hour_num[4]),
    .B(hour[4]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o211a_2 _349_ (
    .A1(_036_),
    .A2(hour_num[0]),
    .B1(_068_),
    .C1(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand3_2 _350_ (
    .A(_062_),
    .B(_067_),
    .C(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_2 _351_ (
    .A(_034_),
    .B(_072_),
    .Y(\hour_inst.done_inc )
  );
  sky130_fd_sc_hd__or3b_2 _352_ (
    .A(day[4]),
    .B(day[3]),
    .C_N(day[0]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor3_2 _353_ (
    .A(day[1]),
    .B(day[2]),
    .C(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and2_2 _354_ (
    .A(dec[3]),
    .B(_074_),
    .X(\day_inst.done_dec )
  );
  sky130_fd_sc_hd__and2b_2 _355_ (
    .A_N(day_num[3]),
    .B(day[3]),
    .X(_075_)
  );
  sky130_fd_sc_hd__nand2b_2 _356_ (
    .A_N(day[3]),
    .B(day_num[3]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xor2_2 _357_ (
    .A(day[2]),
    .B(day_num[2]),
    .X(_077_)
  );
  sky130_fd_sc_hd__or3b_2 _358_ (
    .A(_075_),
    .B(_077_),
    .C_N(_076_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2b_2 _359_ (
    .A_N(day[1]),
    .B(day_num[1]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2b_2 _360_ (
    .A_N(day[0]),
    .B(day_num[0]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__and2b_2 _361_ (
    .A_N(day_num[1]),
    .B(day[1]),
    .X(_081_)
  );
  sky130_fd_sc_hd__a21o_2 _362_ (
    .A1(day[0]),
    .A2(_039_),
    .B1(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__and2b_2 _363_ (
    .A_N(day_num[4]),
    .B(day[4]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand2b_2 _364_ (
    .A_N(day_num[4]),
    .B(day[4]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2b_2 _365_ (
    .A_N(day[4]),
    .B(day_num[4]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and4_2 _366_ (
    .A(_079_),
    .B(_080_),
    .C(_084_),
    .D(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__or3b_2 _367_ (
    .A(_078_),
    .B(_082_),
    .C_N(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nor2_2 _368_ (
    .A(_033_),
    .B(_087_),
    .Y(\day_inst.done_inc )
  );
  sky130_fd_sc_hd__nor3_2 _369_ (
    .A(month[1]),
    .B(month[2]),
    .C(month[3]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__and3_2 _370_ (
    .A(dec[4]),
    .B(month[0]),
    .C(_088_),
    .X(\month_inst.done_dec )
  );
  sky130_fd_sc_hd__nor2_2 _371_ (
    .A(month[0]),
    .B(month[1]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_2 _372_ (
    .A(month[2]),
    .B(month[3]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__and4_2 _373_ (
    .A(inc[4]),
    .B(month[2]),
    .C(month[3]),
    .D(_089_),
    .X(\month_inst.done_inc )
  );
  sky130_fd_sc_hd__and2b_2 _374_ (
    .A_N(inc[4]),
    .B(dec[4]),
    .X(_091_)
  );
  sky130_fd_sc_hd__inv_2 _375_ (
    .A(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__and2b_2 _376_ (
    .A_N(dec[4]),
    .B(inc[4]),
    .X(_093_)
  );
  sky130_fd_sc_hd__o21ai_2 _377_ (
    .A1(_091_),
    .A2(_093_),
    .B1(en[4]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_2 _378_ (
    .A(month[0]),
    .B(_090_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _379_ (
    .A0(_095_),
    .A1(month[0]),
    .S(_094_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_2 _380_ (
    .A(month[0]),
    .B(month[1]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand3b_2 _381_ (
    .A_N(_089_),
    .B(_090_),
    .C(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xnor2_2 _382_ (
    .A(_091_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _383_ (
    .A0(_098_),
    .A1(month[1]),
    .S(_094_),
    .X(_001_)
  );
  sky130_fd_sc_hd__o21ai_2 _384_ (
    .A1(month[0]),
    .A2(month[1]),
    .B1(month[2]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a211o_2 _385_ (
    .A1(month[0]),
    .A2(month[3]),
    .B1(month[2]),
    .C1(month[1]),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _386_ (
    .A0(month[3]),
    .A1(_100_),
    .S(_099_),
    .X(_101_)
  );
  sky130_fd_sc_hd__and3_2 _387_ (
    .A(month[0]),
    .B(month[1]),
    .C(month[2]),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_2 _388_ (
    .A1(month[0]),
    .A2(month[1]),
    .B1(month[2]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a2111o_2 _389_ (
    .A1(month[2]),
    .A2(month[3]),
    .B1(_091_),
    .C1(_102_),
    .D1(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__o21ai_2 _390_ (
    .A1(_092_),
    .A2(_101_),
    .B1(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _391_ (
    .A0(_105_),
    .A1(month[2]),
    .S(_094_),
    .X(_002_)
  );
  sky130_fd_sc_hd__o31a_2 _392_ (
    .A1(month[0]),
    .A2(month[1]),
    .A3(month[2]),
    .B1(month[3]),
    .X(_106_)
  );
  sky130_fd_sc_hd__o21a_2 _393_ (
    .A1(_088_),
    .A2(_106_),
    .B1(_091_),
    .X(_107_)
  );
  sky130_fd_sc_hd__or2_2 _394_ (
    .A(month[3]),
    .B(_102_),
    .X(_108_)
  );
  sky130_fd_sc_hd__a31o_2 _395_ (
    .A1(_090_),
    .A2(_092_),
    .A3(_108_),
    .B1(_107_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _396_ (
    .A0(_109_),
    .A1(month[3]),
    .S(_094_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor2_2 _397_ (
    .A(inc[2]),
    .B(_035_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_2 _398_ (
    .A(_034_),
    .B(dec[2]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o21a_2 _399_ (
    .A1(_110_),
    .A2(_111_),
    .B1(en[2]),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_2 _400_ (
    .A1(_110_),
    .A2(_111_),
    .B1(en[2]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__and2b_2 _401_ (
    .A_N(_064_),
    .B(_065_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_2 _402_ (
    .A(_063_),
    .B(_070_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a21bo_2 _403_ (
    .A1(_059_),
    .A2(_061_),
    .B1_N(_060_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a211o_2 _404_ (
    .A1(_067_),
    .A2(_116_),
    .B1(_115_),
    .C1(_114_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a21oi_2 _405_ (
    .A1(_068_),
    .A2(_117_),
    .B1(_110_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand3_2 _406_ (
    .A(_068_),
    .B(_072_),
    .C(_117_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21a_2 _407_ (
    .A1(hour_num[0]),
    .A2(_058_),
    .B1(_036_),
    .X(_120_)
  );
  sky130_fd_sc_hd__a31o_2 _408_ (
    .A1(_068_),
    .A2(_072_),
    .A3(_117_),
    .B1(_120_),
    .X(_121_)
  );
  sky130_fd_sc_hd__o211a_2 _409_ (
    .A1(_038_),
    .A2(_119_),
    .B1(_121_),
    .C1(_110_),
    .X(_122_)
  );
  sky130_fd_sc_hd__a21o_2 _410_ (
    .A1(_036_),
    .A2(_118_),
    .B1(_113_),
    .X(_123_)
  );
  sky130_fd_sc_hd__o22a_2 _411_ (
    .A1(hour[0]),
    .A2(_112_),
    .B1(_122_),
    .B2(_123_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_2 _412_ (
    .A(hour[1]),
    .B(hour[0]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _413_ (
    .A1_N(_055_),
    .A2_N(_124_),
    .B1(_058_),
    .B2(hour_num[1]),
    .X(_125_)
  );
  sky130_fd_sc_hd__a31o_2 _414_ (
    .A1(_068_),
    .A2(_072_),
    .A3(_117_),
    .B1(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _415_ (
    .A(hour_num[0]),
    .B(hour_num[1]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__and2_2 _416_ (
    .A(hour_num[0]),
    .B(hour_num[1]),
    .X(_128_)
  );
  sky130_fd_sc_hd__o311a_2 _417_ (
    .A1(_119_),
    .A2(_127_),
    .A3(_128_),
    .B1(_126_),
    .C1(_110_),
    .X(_129_)
  );
  sky130_fd_sc_hd__a31o_2 _418_ (
    .A1(_055_),
    .A2(_118_),
    .A3(_124_),
    .B1(_113_),
    .X(_130_)
  );
  sky130_fd_sc_hd__o22a_2 _419_ (
    .A1(hour[1]),
    .A2(_112_),
    .B1(_129_),
    .B2(_130_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and2_2 _420_ (
    .A(hour[2]),
    .B(_055_),
    .X(_131_)
  );
  sky130_fd_sc_hd__o22a_2 _421_ (
    .A1(hour_num[2]),
    .A2(_058_),
    .B1(_131_),
    .B2(_056_),
    .X(_132_)
  );
  sky130_fd_sc_hd__a31o_2 _422_ (
    .A1(_068_),
    .A2(_072_),
    .A3(_117_),
    .B1(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__and2b_2 _423_ (
    .A_N(hour_num[2]),
    .B(_127_),
    .X(_134_)
  );
  sky130_fd_sc_hd__o21a_2 _424_ (
    .A1(hour_num[0]),
    .A2(hour_num[1]),
    .B1(hour_num[2]),
    .X(_135_)
  );
  sky130_fd_sc_hd__o311a_2 _425_ (
    .A1(_119_),
    .A2(_134_),
    .A3(_135_),
    .B1(_133_),
    .C1(_110_),
    .X(_136_)
  );
  sky130_fd_sc_hd__a21o_2 _426_ (
    .A1(hour[1]),
    .A2(hour[0]),
    .B1(hour[2]),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand3_2 _427_ (
    .A(hour[1]),
    .B(hour[0]),
    .C(hour[2]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a31o_2 _428_ (
    .A1(_118_),
    .A2(_137_),
    .A3(_138_),
    .B1(_113_),
    .X(_139_)
  );
  sky130_fd_sc_hd__o22a_2 _429_ (
    .A1(hour[2]),
    .A2(_112_),
    .B1(_136_),
    .B2(_139_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _430_ (
    .A(_037_),
    .B(_056_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ba_2 _431_ (
    .A1(hour[4]),
    .A2(hour_num[3]),
    .B1_N(_057_),
    .X(_141_)
  );
  sky130_fd_sc_hd__a311o_2 _432_ (
    .A1(_068_),
    .A2(_072_),
    .A3(_117_),
    .B1(_140_),
    .C1(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__and2b_2 _433_ (
    .A_N(_134_),
    .B(hour_num[3]),
    .X(_143_)
  );
  sky130_fd_sc_hd__and2b_2 _434_ (
    .A_N(hour_num[3]),
    .B(_134_),
    .X(_144_)
  );
  sky130_fd_sc_hd__o311a_2 _435_ (
    .A1(_119_),
    .A2(_143_),
    .A3(_144_),
    .B1(_142_),
    .C1(_110_),
    .X(_145_)
  );
  sky130_fd_sc_hd__or2_2 _436_ (
    .A(_037_),
    .B(_138_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nand2_2 _437_ (
    .A(_037_),
    .B(_138_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a31o_2 _438_ (
    .A1(_118_),
    .A2(_146_),
    .A3(_147_),
    .B1(_113_),
    .X(_148_)
  );
  sky130_fd_sc_hd__o22a_2 _439_ (
    .A1(hour[3]),
    .A2(_112_),
    .B1(_145_),
    .B2(_148_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _440_ (
    .A0(_069_),
    .A1(hour[4]),
    .S(_057_),
    .X(_149_)
  );
  sky130_fd_sc_hd__xor2_2 _441_ (
    .A(hour_num[4]),
    .B(_144_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a31o_2 _442_ (
    .A1(_068_),
    .A2(_072_),
    .A3(_117_),
    .B1(_149_),
    .X(_151_)
  );
  sky130_fd_sc_hd__o211a_2 _443_ (
    .A1(_119_),
    .A2(_150_),
    .B1(_151_),
    .C1(_110_),
    .X(_152_)
  );
  sky130_fd_sc_hd__xnor2_2 _444_ (
    .A(hour[4]),
    .B(_146_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21o_2 _445_ (
    .A1(_118_),
    .A2(_153_),
    .B1(_113_),
    .X(_154_)
  );
  sky130_fd_sc_hd__o22a_2 _446_ (
    .A1(hour[4]),
    .A2(_112_),
    .B1(_152_),
    .B2(_154_),
    .X(_008_)
  );
  sky130_fd_sc_hd__and2_2 _447_ (
    .A(_033_),
    .B(dec[3]),
    .X(_155_)
  );
  sky130_fd_sc_hd__nand2_2 _448_ (
    .A(_033_),
    .B(dec[3]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_2 _449_ (
    .A(_033_),
    .B(dec[3]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21a_2 _450_ (
    .A1(_155_),
    .A2(_157_),
    .B1(en[3]),
    .X(_158_)
  );
  sky130_fd_sc_hd__inv_2 _451_ (
    .A(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_2 _452_ (
    .A1(_079_),
    .A2(_080_),
    .B1(_081_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a311o_2 _453_ (
    .A1(day[2]),
    .A2(_040_),
    .A3(_076_),
    .B1(_083_),
    .C1(_075_),
    .X(_161_)
  );
  sky130_fd_sc_hd__o21bai_2 _454_ (
    .A1(_078_),
    .A2(_160_),
    .B1_N(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21o_2 _455_ (
    .A1(_085_),
    .A2(_162_),
    .B1(_155_),
    .X(_163_)
  );
  sky130_fd_sc_hd__nand3_2 _456_ (
    .A(_085_),
    .B(_087_),
    .C(_162_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21o_2 _457_ (
    .A1(day_num[0]),
    .A2(_074_),
    .B1(_156_),
    .X(_165_)
  );
  sky130_fd_sc_hd__a31o_2 _458_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_162_),
    .B1(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__a21bo_2 _459_ (
    .A1(_163_),
    .A2(_166_),
    .B1_N(day[0]),
    .X(_167_)
  );
  sky130_fd_sc_hd__o31a_2 _460_ (
    .A1(_039_),
    .A2(_156_),
    .A3(_164_),
    .B1(_158_),
    .X(_168_)
  );
  sky130_fd_sc_hd__a22o_2 _461_ (
    .A1(day[0]),
    .A2(_159_),
    .B1(_167_),
    .B2(_168_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_2 _462_ (
    .A(day_num[1]),
    .B(_074_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__and2_2 _463_ (
    .A(day[0]),
    .B(day[1]),
    .X(_170_)
  );
  sky130_fd_sc_hd__nor2_2 _464_ (
    .A(day[0]),
    .B(day[1]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_2 _465_ (
    .A(_170_),
    .B(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xor2_2 _466_ (
    .A(day_num[0]),
    .B(day_num[1]),
    .X(_173_)
  );
  sky130_fd_sc_hd__a41o_2 _467_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_162_),
    .A4(_173_),
    .B1(_156_),
    .X(_174_)
  );
  sky130_fd_sc_hd__a31o_2 _468_ (
    .A1(_164_),
    .A2(_169_),
    .A3(_172_),
    .B1(_174_),
    .X(_175_)
  );
  sky130_fd_sc_hd__o31a_2 _469_ (
    .A1(_163_),
    .A2(_170_),
    .A3(_171_),
    .B1(_158_),
    .X(_176_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _470_ (
    .A1_N(_175_),
    .A2_N(_176_),
    .B1(day[1]),
    .B2(_158_),
    .X(_010_)
  );
  sky130_fd_sc_hd__or3_2 _471_ (
    .A(day_num[0]),
    .B(day_num[1]),
    .C(day_num[2]),
    .X(_177_)
  );
  sky130_fd_sc_hd__o21ai_2 _472_ (
    .A1(day_num[0]),
    .A2(day_num[1]),
    .B1(day_num[2]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__and2_2 _473_ (
    .A(_177_),
    .B(_178_),
    .X(_179_)
  );
  sky130_fd_sc_hd__and4_2 _474_ (
    .A(_085_),
    .B(_087_),
    .C(_162_),
    .D(_179_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nand2_2 _475_ (
    .A(day_num[2]),
    .B(_074_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o21ai_2 _476_ (
    .A1(day[0]),
    .A2(day[1]),
    .B1(day[2]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__or3_2 _477_ (
    .A(day[0]),
    .B(day[1]),
    .C(day[2]),
    .X(_183_)
  );
  sky130_fd_sc_hd__and3_2 _478_ (
    .A(_181_),
    .B(_182_),
    .C(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__a211o_2 _479_ (
    .A1(_164_),
    .A2(_184_),
    .B1(_180_),
    .C1(_156_),
    .X(_185_)
  );
  sky130_fd_sc_hd__and3_2 _480_ (
    .A(day[0]),
    .B(day[1]),
    .C(day[2]),
    .X(_186_)
  );
  sky130_fd_sc_hd__nor2_2 _481_ (
    .A(day[2]),
    .B(_170_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o31a_2 _482_ (
    .A1(_163_),
    .A2(_186_),
    .A3(_187_),
    .B1(_158_),
    .X(_188_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _483_ (
    .A1_N(_185_),
    .A2_N(_188_),
    .B1(day[2]),
    .B2(_158_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor2_2 _484_ (
    .A(day_num[3]),
    .B(_177_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xor2_2 _485_ (
    .A(day_num[3]),
    .B(_177_),
    .X(_190_)
  );
  sky130_fd_sc_hd__and4_2 _486_ (
    .A(_085_),
    .B(_087_),
    .C(_162_),
    .D(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__or2_2 _487_ (
    .A(day[3]),
    .B(_183_),
    .X(_192_)
  );
  sky130_fd_sc_hd__a22oi_2 _488_ (
    .A1(day_num[3]),
    .A2(_074_),
    .B1(_183_),
    .B2(day[3]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a311o_2 _489_ (
    .A1(_164_),
    .A2(_192_),
    .A3(_193_),
    .B1(_191_),
    .C1(_156_),
    .X(_194_)
  );
  sky130_fd_sc_hd__nand2_2 _490_ (
    .A(day[3]),
    .B(_186_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__or2_2 _491_ (
    .A(day[3]),
    .B(_186_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nand2_2 _492_ (
    .A(_195_),
    .B(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21a_2 _493_ (
    .A1(_163_),
    .A2(_197_),
    .B1(_158_),
    .X(_198_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _494_ (
    .A1_N(_194_),
    .A2_N(_198_),
    .B1(day[3]),
    .B2(_158_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_2 _495_ (
    .A(day[4]),
    .B(_192_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2_2 _496_ (
    .A(day_num[4]),
    .B(_074_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o211a_2 _497_ (
    .A1(day[4]),
    .A2(_192_),
    .B1(_199_),
    .C1(_200_),
    .X(_201_)
  );
  sky130_fd_sc_hd__xnor2_2 _498_ (
    .A(day_num[4]),
    .B(_189_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a41o_2 _499_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_162_),
    .A4(_202_),
    .B1(_156_),
    .X(_203_)
  );
  sky130_fd_sc_hd__a21oi_2 _500_ (
    .A1(_164_),
    .A2(_201_),
    .B1(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xor2_2 _501_ (
    .A(day[4]),
    .B(_195_),
    .X(_205_)
  );
  sky130_fd_sc_hd__o21ai_2 _502_ (
    .A1(_163_),
    .A2(_205_),
    .B1(_158_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o22a_2 _503_ (
    .A1(day[4]),
    .A2(_158_),
    .B1(_204_),
    .B2(_206_),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2b_2 _504_ (
    .A_N(inc[5]),
    .B(dec[5]),
    .X(_207_)
  );
  sky130_fd_sc_hd__and2b_2 _505_ (
    .A_N(dec[5]),
    .B(inc[5]),
    .X(_208_)
  );
  sky130_fd_sc_hd__o21ai_2 _506_ (
    .A1(_207_),
    .A2(_208_),
    .B1(en[5]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_2 _507_ (
    .A(year[1]),
    .B(year[0]),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21a_2 _508_ (
    .A1(year[1]),
    .A2(year[0]),
    .B1(year[2]),
    .X(_211_)
  );
  sky130_fd_sc_hd__o311a_2 _509_ (
    .A1(year[4]),
    .A2(year[3]),
    .A3(_211_),
    .B1(year[6]),
    .C1(year[5]),
    .X(_212_)
  );
  sky130_fd_sc_hd__inv_2 _510_ (
    .A(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__and4b_2 _511_ (
    .A_N(year[4]),
    .B(_042_),
    .C(_210_),
    .D(year[5]),
    .X(_214_)
  );
  sky130_fd_sc_hd__a31o_2 _512_ (
    .A1(year[2]),
    .A2(year[6]),
    .A3(_214_),
    .B1(_212_),
    .X(_215_)
  );
  sky130_fd_sc_hd__nor2_2 _513_ (
    .A(_207_),
    .B(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__or3_2 _514_ (
    .A(year[2]),
    .B(year[1]),
    .C(year[0]),
    .X(_217_)
  );
  sky130_fd_sc_hd__or4_2 _515_ (
    .A(year[3]),
    .B(year[2]),
    .C(year[1]),
    .D(year[0]),
    .X(_218_)
  );
  sky130_fd_sc_hd__nor2_2 _516_ (
    .A(year[4]),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__or4_2 _517_ (
    .A(year[5]),
    .B(year[4]),
    .C(year[6]),
    .D(_218_),
    .X(_220_)
  );
  sky130_fd_sc_hd__a21o_2 _518_ (
    .A1(_207_),
    .A2(_220_),
    .B1(_216_),
    .X(_221_)
  );
  sky130_fd_sc_hd__a21oi_2 _519_ (
    .A1(year[0]),
    .A2(_213_),
    .B1(_209_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a22o_2 _520_ (
    .A1(year[0]),
    .A2(_209_),
    .B1(_221_),
    .B2(_222_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _521_ (
    .A(year[1]),
    .B(year[0]),
    .X(_223_)
  );
  sky130_fd_sc_hd__o21a_2 _522_ (
    .A1(_210_),
    .A2(_223_),
    .B1(_220_),
    .X(_224_)
  );
  sky130_fd_sc_hd__nor2_2 _523_ (
    .A(_212_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nor2_2 _524_ (
    .A(_207_),
    .B(_210_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(_207_),
    .A1(_226_),
    .S(_225_),
    .X(_227_)
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(_227_),
    .A1(year[1]),
    .S(_209_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2b_2 _527_ (
    .A_N(_211_),
    .B(_217_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__and2b_2 _528_ (
    .A_N(_212_),
    .B(_207_),
    .X(_229_)
  );
  sky130_fd_sc_hd__nor2_2 _529_ (
    .A(year[2]),
    .B(_223_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__and3_2 _530_ (
    .A(year[2]),
    .B(year[1]),
    .C(year[0]),
    .X(_231_)
  );
  sky130_fd_sc_hd__nor2_2 _531_ (
    .A(_230_),
    .B(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a22o_2 _532_ (
    .A1(_228_),
    .A2(_229_),
    .B1(_232_),
    .B2(_216_),
    .X(_233_)
  );
  sky130_fd_sc_hd__mux2_1 _533_ (
    .A0(_233_),
    .A1(year[2]),
    .S(_209_),
    .X(_016_)
  );
  sky130_fd_sc_hd__a21oi_2 _534_ (
    .A1(_207_),
    .A2(_217_),
    .B1(_209_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o21a_2 _535_ (
    .A1(_207_),
    .A2(_231_),
    .B1(_234_),
    .X(_235_)
  );
  sky130_fd_sc_hd__o211a_2 _536_ (
    .A1(_042_),
    .A2(_217_),
    .B1(_220_),
    .C1(_229_),
    .X(_236_)
  );
  sky130_fd_sc_hd__a21boi_2 _537_ (
    .A1(year[3]),
    .A2(_231_),
    .B1_N(_216_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__o32a_2 _538_ (
    .A1(_209_),
    .A2(_236_),
    .A3(_237_),
    .B1(_235_),
    .B2(year[3]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _539_ (
    .A(year[4]),
    .B(_218_),
    .X(_238_)
  );
  sky130_fd_sc_hd__o211a_2 _540_ (
    .A1(_219_),
    .A2(_238_),
    .B1(_229_),
    .C1(_220_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nand3_2 _541_ (
    .A(year[4]),
    .B(year[3]),
    .C(_231_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a21o_2 _542_ (
    .A1(year[3]),
    .A2(_231_),
    .B1(year[4]),
    .X(_241_)
  );
  sky130_fd_sc_hd__a31o_2 _543_ (
    .A1(_216_),
    .A2(_240_),
    .A3(_241_),
    .B1(_239_),
    .X(_242_)
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(_242_),
    .A1(year[4]),
    .S(_209_),
    .X(_018_)
  );
  sky130_fd_sc_hd__xnor2_2 _545_ (
    .A(_041_),
    .B(_219_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_2 _546_ (
    .A(_041_),
    .B(_240_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__or2_2 _547_ (
    .A(_041_),
    .B(_240_),
    .X(_245_)
  );
  sky130_fd_sc_hd__a32o_2 _548_ (
    .A1(_216_),
    .A2(_244_),
    .A3(_245_),
    .B1(_243_),
    .B2(_207_),
    .X(_246_)
  );
  sky130_fd_sc_hd__mux2_1 _549_ (
    .A0(_246_),
    .A1(year[5]),
    .S(_209_),
    .X(_019_)
  );
  sky130_fd_sc_hd__a21bo_2 _550_ (
    .A1(_041_),
    .A2(_219_),
    .B1_N(year[6]),
    .X(_247_)
  );
  sky130_fd_sc_hd__nand2_2 _551_ (
    .A(_220_),
    .B(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand2b_2 _552_ (
    .A_N(year[6]),
    .B(_245_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__a22o_2 _553_ (
    .A1(_207_),
    .A2(_248_),
    .B1(_249_),
    .B2(_216_),
    .X(_250_)
  );
  sky130_fd_sc_hd__mux2_1 _554_ (
    .A0(_250_),
    .A1(year[6]),
    .S(_209_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2b_2 _555_ (
    .A_N(inc[1]),
    .B(dec[1]),
    .X(_251_)
  );
  sky130_fd_sc_hd__nand2b_2 _556_ (
    .A_N(inc[1]),
    .B(dec[1]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__and2b_2 _557_ (
    .A_N(dec[1]),
    .B(inc[1]),
    .X(_253_)
  );
  sky130_fd_sc_hd__o21ai_2 _558_ (
    .A1(_251_),
    .A2(_253_),
    .B1(en[1]),
    .Y(_254_)
  );
  sky130_fd_sc_hd__inv_2 _559_ (
    .A(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__a21oi_2 _560_ (
    .A1(minute[2]),
    .A2(_053_),
    .B1(minute[0]),
    .Y(_256_)
  );
  sky130_fd_sc_hd__mux2_1 _561_ (
    .A0(_256_),
    .A1(minute[0]),
    .S(_254_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a211o_2 _562_ (
    .A1(minute[2]),
    .A2(_053_),
    .B1(_054_),
    .C1(_048_),
    .X(_257_)
  );
  sky130_fd_sc_hd__xnor2_2 _563_ (
    .A(_251_),
    .B(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__mux2_1 _564_ (
    .A0(minute[1]),
    .A1(_258_),
    .S(_255_),
    .X(_022_)
  );
  sky130_fd_sc_hd__o21ai_2 _565_ (
    .A1(minute[1]),
    .A2(minute[0]),
    .B1(minute[2]),
    .Y(_259_)
  );
  sky130_fd_sc_hd__a221o_2 _566_ (
    .A1(minute[2]),
    .A2(_053_),
    .B1(_259_),
    .B2(_049_),
    .C1(_252_),
    .X(_260_)
  );
  sky130_fd_sc_hd__or2_2 _567_ (
    .A(minute[2]),
    .B(_054_),
    .X(_261_)
  );
  sky130_fd_sc_hd__a21o_2 _568_ (
    .A1(_053_),
    .A2(_261_),
    .B1(_251_),
    .X(_262_)
  );
  sky130_fd_sc_hd__and3_2 _569_ (
    .A(minute[1]),
    .B(minute[0]),
    .C(minute[2]),
    .X(_263_)
  );
  sky130_fd_sc_hd__or3b_2 _570_ (
    .A(_262_),
    .B(_263_),
    .C_N(_261_),
    .X(_264_)
  );
  sky130_fd_sc_hd__o21ai_2 _571_ (
    .A1(_052_),
    .A2(_260_),
    .B1(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__mux2_1 _572_ (
    .A0(minute[2]),
    .A1(_265_),
    .S(_255_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nand2_2 _573_ (
    .A(minute[3]),
    .B(_049_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a21o_2 _574_ (
    .A1(_050_),
    .A2(_266_),
    .B1(_252_),
    .X(_267_)
  );
  sky130_fd_sc_hd__and2_2 _575_ (
    .A(minute[3]),
    .B(_263_),
    .X(_268_)
  );
  sky130_fd_sc_hd__nor2_2 _576_ (
    .A(minute[3]),
    .B(_263_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__o311a_2 _577_ (
    .A1(_262_),
    .A2(_268_),
    .A3(_269_),
    .B1(_267_),
    .C1(_255_),
    .X(_270_)
  );
  sky130_fd_sc_hd__o21ba_2 _578_ (
    .A1(minute[3]),
    .A2(_255_),
    .B1_N(_270_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a21oi_2 _579_ (
    .A1(minute[4]),
    .A2(_268_),
    .B1(_251_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__a21oi_2 _580_ (
    .A1(minute[4]),
    .A2(_268_),
    .B1(_262_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__a22o_2 _581_ (
    .A1(_051_),
    .A2(_251_),
    .B1(_268_),
    .B2(_272_),
    .X(_273_)
  );
  sky130_fd_sc_hd__a211o_2 _582_ (
    .A1(_050_),
    .A2(_251_),
    .B1(_254_),
    .C1(_272_),
    .X(_274_)
  );
  sky130_fd_sc_hd__a22o_2 _583_ (
    .A1(_255_),
    .A2(_273_),
    .B1(_274_),
    .B2(minute[4]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_2 _584_ (
    .A(_051_),
    .B(_252_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__or3_2 _585_ (
    .A(_254_),
    .B(_272_),
    .C(_275_),
    .X(_276_)
  );
  sky130_fd_sc_hd__or4_2 _586_ (
    .A(minute[5]),
    .B(_254_),
    .C(_271_),
    .D(_275_),
    .X(_277_)
  );
  sky130_fd_sc_hd__a21bo_2 _587_ (
    .A1(minute[5]),
    .A2(_276_),
    .B1_N(_277_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2b_2 _588_ (
    .A_N(inc[0]),
    .B(dec[0]),
    .X(_278_)
  );
  sky130_fd_sc_hd__and2b_2 _589_ (
    .A_N(dec[0]),
    .B(inc[0]),
    .X(_279_)
  );
  sky130_fd_sc_hd__o21ai_2 _590_ (
    .A1(_278_),
    .A2(_279_),
    .B1(en[0]),
    .Y(_280_)
  );
  sky130_fd_sc_hd__inv_2 _591_ (
    .A(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_2 _592_ (
    .A(second[2]),
    .B(_046_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_2 _593_ (
    .A1(second[2]),
    .A2(_046_),
    .B1(second[0]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__mux2_1 _594_ (
    .A0(_283_),
    .A1(second[0]),
    .S(_280_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_2 _595_ (
    .A(_043_),
    .B(_282_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nor2_2 _596_ (
    .A(_047_),
    .B(_284_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__xor2_2 _597_ (
    .A(_278_),
    .B(_285_),
    .X(_286_)
  );
  sky130_fd_sc_hd__mux2_1 _598_ (
    .A0(second[1]),
    .A1(_286_),
    .S(_281_),
    .X(_028_)
  );
  sky130_fd_sc_hd__xnor2_2 _599_ (
    .A(second[2]),
    .B(_043_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__and4b_2 _600_ (
    .A_N(_045_),
    .B(_278_),
    .C(_282_),
    .D(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd__or2_2 _601_ (
    .A(second[2]),
    .B(_047_),
    .X(_289_)
  );
  sky130_fd_sc_hd__a21oi_2 _602_ (
    .A1(_046_),
    .A2(_289_),
    .B1(_278_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__and3_2 _603_ (
    .A(second[0]),
    .B(second[1]),
    .C(second[2]),
    .X(_291_)
  );
  sky130_fd_sc_hd__inv_2 _604_ (
    .A(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__a31o_2 _605_ (
    .A1(_289_),
    .A2(_290_),
    .A3(_292_),
    .B1(_280_),
    .X(_293_)
  );
  sky130_fd_sc_hd__o22a_2 _606_ (
    .A1(second[2]),
    .A2(_281_),
    .B1(_288_),
    .B2(_293_),
    .X(_029_)
  );
  sky130_fd_sc_hd__o21ai_2 _607_ (
    .A1(second[2]),
    .A2(_043_),
    .B1(second[3]),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nand2_2 _608_ (
    .A(_044_),
    .B(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__and2_2 _609_ (
    .A(second[3]),
    .B(_291_),
    .X(_296_)
  );
  sky130_fd_sc_hd__o21ai_2 _610_ (
    .A1(second[3]),
    .A2(_291_),
    .B1(_290_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _611_ (
    .A1_N(_296_),
    .A2_N(_297_),
    .B1(_278_),
    .B2(_295_),
    .X(_298_)
  );
  sky130_fd_sc_hd__mux2_1 _612_ (
    .A0(second[3]),
    .A1(_298_),
    .S(_281_),
    .X(_030_)
  );
  sky130_fd_sc_hd__o21ai_2 _613_ (
    .A1(second[4]),
    .A2(_296_),
    .B1(_290_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__a21oi_2 _614_ (
    .A1(second[4]),
    .A2(_296_),
    .B1(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__xnor2_2 _615_ (
    .A(second[4]),
    .B(_044_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__a21o_2 _616_ (
    .A1(_278_),
    .A2(_301_),
    .B1(_280_),
    .X(_302_)
  );
  sky130_fd_sc_hd__o22a_2 _617_ (
    .A1(second[4]),
    .A2(_281_),
    .B1(_300_),
    .B2(_302_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a32o_2 _618_ (
    .A1(second[4]),
    .A2(_290_),
    .A3(_296_),
    .B1(_045_),
    .B2(_278_),
    .X(_303_)
  );
  sky130_fd_sc_hd__o21a_2 _619_ (
    .A1(second[4]),
    .A2(_044_),
    .B1(_278_),
    .X(_304_)
  );
  sky130_fd_sc_hd__or3_2 _620_ (
    .A(_280_),
    .B(_290_),
    .C(_304_),
    .X(_305_)
  );
  sky130_fd_sc_hd__a22o_2 _621_ (
    .A1(_281_),
    .A2(_303_),
    .B1(_305_),
    .B2(second[5]),
    .X(_032_)
  );
  sky130_fd_sc_hd__dfstp_2 _622_ (
    .CLK(clk),
    .D(_000_),
    .Q(month[0]),
    .SET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _623_ (
    .CLK(clk),
    .D(_001_),
    .Q(month[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _624_ (
    .CLK(clk),
    .D(_002_),
    .Q(month[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _625_ (
    .CLK(clk),
    .D(_003_),
    .Q(month[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _626_ (
    .CLK(clk),
    .D(_004_),
    .Q(hour[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _627_ (
    .CLK(clk),
    .D(_005_),
    .Q(hour[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _628_ (
    .CLK(clk),
    .D(_006_),
    .Q(hour[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _629_ (
    .CLK(clk),
    .D(_007_),
    .Q(hour[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _630_ (
    .CLK(clk),
    .D(_008_),
    .Q(hour[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfstp_2 _631_ (
    .CLK(clk),
    .D(_009_),
    .Q(day[0]),
    .SET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _632_ (
    .CLK(clk),
    .D(_010_),
    .Q(day[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _633_ (
    .CLK(clk),
    .D(_011_),
    .Q(day[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _634_ (
    .CLK(clk),
    .D(_012_),
    .Q(day[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _635_ (
    .CLK(clk),
    .D(_013_),
    .Q(day[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _636_ (
    .CLK(clk),
    .D(_014_),
    .Q(year[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _637_ (
    .CLK(clk),
    .D(_015_),
    .Q(year[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _638_ (
    .CLK(clk),
    .D(_016_),
    .Q(year[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _639_ (
    .CLK(clk),
    .D(_017_),
    .Q(year[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _640_ (
    .CLK(clk),
    .D(_018_),
    .Q(year[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _641_ (
    .CLK(clk),
    .D(_019_),
    .Q(year[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _642_ (
    .CLK(clk),
    .D(_020_),
    .Q(year[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _643_ (
    .CLK(clk),
    .D(_021_),
    .Q(minute[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _644_ (
    .CLK(clk),
    .D(_022_),
    .Q(minute[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _645_ (
    .CLK(clk),
    .D(_023_),
    .Q(minute[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _646_ (
    .CLK(clk),
    .D(_024_),
    .Q(minute[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _647_ (
    .CLK(clk),
    .D(_025_),
    .Q(minute[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _648_ (
    .CLK(clk),
    .D(_026_),
    .Q(minute[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _649_ (
    .CLK(clk),
    .D(_027_),
    .Q(second[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _650_ (
    .CLK(clk),
    .D(_028_),
    .Q(second[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _651_ (
    .CLK(clk),
    .D(_029_),
    .Q(second[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _652_ (
    .CLK(clk),
    .D(_030_),
    .Q(second[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _653_ (
    .CLK(clk),
    .D(_031_),
    .Q(second[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _654_ (
    .CLK(clk),
    .D(_032_),
    .Q(second[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__buf_2 _655_ (
    .A(\second_inst.done_dec ),
    .X(done_dec[0])
  );
  sky130_fd_sc_hd__buf_2 _656_ (
    .A(\minute_inst.done_dec ),
    .X(done_dec[1])
  );
  sky130_fd_sc_hd__buf_2 _657_ (
    .A(\hour_inst.done_dec ),
    .X(done_dec[2])
  );
  sky130_fd_sc_hd__buf_2 _658_ (
    .A(\day_inst.done_dec ),
    .X(done_dec[3])
  );
  sky130_fd_sc_hd__buf_2 _659_ (
    .A(\month_inst.done_dec ),
    .X(done_dec[4])
  );
  sky130_fd_sc_hd__buf_2 _660_ (
    .A(\second_inst.done_inc ),
    .X(done_inc[0])
  );
  sky130_fd_sc_hd__buf_2 _661_ (
    .A(\minute_inst.done_inc ),
    .X(done_inc[1])
  );
  sky130_fd_sc_hd__buf_2 _662_ (
    .A(\hour_inst.done_inc ),
    .X(done_inc[2])
  );
  sky130_fd_sc_hd__buf_2 _663_ (
    .A(\day_inst.done_inc ),
    .X(done_inc[3])
  );
  sky130_fd_sc_hd__buf_2 _664_ (
    .A(\month_inst.done_inc ),
    .X(done_inc[4])
  );
endmodule
