// Auto-generated by OpenLane
module counter_all(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input reset_n,
  output[4:0] day,
  output[3:0] month,
  output[6:0] year,
  output[4:0] hour,
  output[5:0] minute,
  output[5:0] second,
  input[4:0] day_num,
  input[4:0] hour_num,
  output[4:0] done_inc,
  output[4:0] done_dec,
  input[5:0] inc,
  input[5:0] dec,
  input[5:0] en
);
endmodule
