// Auto-generated by OpenLane
module alarm(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst_n,
  input[5:0] alarm_min,
  input[4:0] alarm_hour,
  input alarm_i,
  input[5:0] minute,
  input[4:0] hour,
  output alarm_o
);
endmodule
