// Auto-generated by OpenLane
module clock_century(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset_n,
  input[1:0] mode,
  input[5:0] select,
  input button_inc,
  input button_dec,
  input am_pm,
  input[5:0] alarm_min,
  input[4:0] alarm_hour,
  input alarm_i,
  output alarm_o,
  output[13:0] led_day,
  output[13:0] led_month,
  output[13:0] led_year,
  output[13:0] led_hour,
  output[13:0] led_min,
  output[13:0] led_sec
);
endmodule
