/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module clock_century(clk, reset_n, mode, select, button_inc, button_dec, am_pm, alarm_min, alarm_hour, alarm_i, alarm_o, led_day, led_month, led_year, led_hour, led_min, led_sec);
  input [4:0] alarm_hour;
  wire [4:0] alarm_hour;
  input alarm_i;
  wire alarm_i;
  input [5:0] alarm_min;
  wire [5:0] alarm_min;
  output alarm_o;
  wire alarm_o;
  input am_pm;
  wire am_pm;
  input button_dec;
  wire button_dec;
  input button_inc;
  wire button_inc;
  input clk;
  wire clk;
  wire \day[0] ;
  wire \day[1] ;
  wire \day[2] ;
  wire \day[3] ;
  wire \day[4] ;
  wire \day_num[0] ;
  wire \day_num[1] ;
  wire \day_num[2] ;
  wire \day_num[3] ;
  wire \day_num[4] ;
  wire \dec[0] ;
  wire \dec[1] ;
  wire \dec[2] ;
  wire \dec[3] ;
  wire \dec[4] ;
  wire \dec[5] ;
  wire \done_dec[0] ;
  wire \done_dec[1] ;
  wire \done_dec[2] ;
  wire \done_dec[3] ;
  wire \done_dec[4] ;
  wire \done_inc[0] ;
  wire \done_inc[1] ;
  wire \done_inc[2] ;
  wire \done_inc[3] ;
  wire \done_inc[4] ;
  wire \en[0] ;
  wire \en[1] ;
  wire \en[2] ;
  wire \en[3] ;
  wire \en[4] ;
  wire \en[5] ;
  wire \hour[0] ;
  wire \hour[1] ;
  wire \hour[2] ;
  wire \hour[3] ;
  wire \hour[4] ;
  wire \hour_num[0] ;
  wire \hour_num[1] ;
  wire \hour_num[2] ;
  wire \hour_num[3] ;
  wire \hour_num[4] ;
  wire \inc[0] ;
  wire \inc[1] ;
  wire \inc[2] ;
  wire \inc[3] ;
  wire \inc[4] ;
  wire \inc[5] ;
  output [13:0] led_day;
  wire [13:0] led_day;
  output [13:0] led_hour;
  wire [13:0] led_hour;
  output [13:0] led_min;
  wire [13:0] led_min;
  output [13:0] led_month;
  wire [13:0] led_month;
  output [13:0] led_sec;
  wire [13:0] led_sec;
  output [13:0] led_year;
  wire [13:0] led_year;
  wire \minute[0] ;
  wire \minute[1] ;
  wire \minute[2] ;
  wire \minute[3] ;
  wire \minute[4] ;
  wire \minute[5] ;
  input [1:0] mode;
  wire [1:0] mode;
  wire \month[0] ;
  wire \month[1] ;
  wire \month[2] ;
  wire \month[3] ;
  input reset_n;
  wire reset_n;
  wire \second[0] ;
  wire \second[1] ;
  wire \second[2] ;
  wire \second[3] ;
  wire \second[4] ;
  wire \second[5] ;
  input [5:0] select;
  wire [5:0] select;
  wire \year[0] ;
  wire \year[1] ;
  wire \year[2] ;
  wire \year[3] ;
  wire \year[4] ;
  wire \year[5] ;
  wire \year[6] ;
  alarm alarm_inst (
    .alarm_hour(alarm_hour),
    .alarm_i(alarm_i),
    .alarm_min(alarm_min),
    .alarm_o(alarm_o),
    .clk(clk),
    .hour({ \hour[4] , \hour[3] , \hour[2] , \hour[1] , \hour[0]  }),
    .minute({ \minute[5] , \minute[4] , \minute[3] , \minute[2] , \minute[1] , \minute[0]  }),
    .rst_n(reset_n)
  );
  counter_all counter_all_inst (
    .clk(clk),
    .day({ \day[4] , \day[3] , \day[2] , \day[1] , \day[0]  }),
    .day_num({ \day_num[4] , \day_num[3] , \day_num[2] , \day_num[1] , \day_num[0]  }),
    .dec({ \dec[5] , \dec[4] , \dec[3] , \dec[2] , \dec[1] , \dec[0]  }),
    .done_dec({ \done_dec[4] , \done_dec[3] , \done_dec[2] , \done_dec[1] , \done_dec[0]  }),
    .done_inc({ \done_inc[4] , \done_inc[3] , \done_inc[2] , \done_inc[1] , \done_inc[0]  }),
    .en({ \en[5] , \en[4] , \en[3] , \en[2] , \en[1] , \en[0]  }),
    .hour({ \hour[4] , \hour[3] , \hour[2] , \hour[1] , \hour[0]  }),
    .hour_num({ \hour_num[4] , \hour_num[3] , \hour_num[2] , \hour_num[1] , \hour_num[0]  }),
    .inc({ \inc[5] , \inc[4] , \inc[3] , \inc[2] , \inc[1] , \inc[0]  }),
    .minute({ \minute[5] , \minute[4] , \minute[3] , \minute[2] , \minute[1] , \minute[0]  }),
    .month({ \month[3] , \month[2] , \month[1] , \month[0]  }),
    .reset_n(reset_n),
    .second({ \second[5] , \second[4] , \second[3] , \second[2] , \second[1] , \second[0]  }),
    .year({ \year[6] , \year[5] , \year[4] , \year[3] , \year[2] , \year[1] , \year[0]  })
  );
  decode_all decode_all_inst (
    .day({ \day[4] , \day[3] , \day[2] , \day[1] , \day[0]  }),
    .hour({ \hour[4] , \hour[3] , \hour[2] , \hour[1] , \hour[0]  }),
    .led_day(led_day),
    .led_hour(led_hour),
    .led_min(led_min),
    .led_month(led_month),
    .led_sec(led_sec),
    .led_year(led_year),
    .minute({ \minute[5] , \minute[4] , \minute[3] , \minute[2] , \minute[1] , \minute[0]  }),
    .month({ \month[3] , \month[2] , \month[1] , \month[0]  }),
    .second({ \second[5] , \second[4] , \second[3] , \second[2] , \second[1] , \second[0]  }),
    .year({ \year[6] , \year[5] , \year[4] , \year[3] , \year[2] , \year[1] , \year[0]  })
  );
  decode_day decode_day_inst (
    .am_pm(am_pm),
    .day_num({ \day_num[4] , \day_num[3] , \day_num[2] , \day_num[1] , \day_num[0]  }),
    .hour_num({ \hour_num[4] , \hour_num[3] , \hour_num[2] , \hour_num[1] , \hour_num[0]  }),
    .month({ \month[3] , \month[2] , \month[1] , \month[0]  }),
    .year({ \year[6] , \year[5] , \year[4] , \year[3] , \year[2] , \year[1] , \year[0]  })
  );
  decode_input decode_input_inst (
    .button_dec(button_dec),
    .button_inc(button_inc),
    .dec({ \dec[5] , \dec[4] , \dec[3] , \dec[2] , \dec[1] , \dec[0]  }),
    .done_dec({ \done_dec[4] , \done_dec[3] , \done_dec[2] , \done_dec[1] , \done_dec[0]  }),
    .done_inc({ \done_inc[4] , \done_inc[3] , \done_inc[2] , \done_inc[1] , \done_inc[0]  }),
    .en({ \en[5] , \en[4] , \en[3] , \en[2] , \en[1] , \en[0]  }),
    .inc({ \inc[5] , \inc[4] , \inc[3] , \inc[2] , \inc[1] , \inc[0]  }),
    .mode(mode),
    .select(select)
  );
endmodule
