// Auto-generated by OpenLane
module decode_all(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input[4:0] day,
  input[3:0] month,
  input[6:0] year,
  input[4:0] hour,
  input[5:0] minute,
  input[5:0] second,
  output[13:0] led_day,
  output[13:0] led_month,
  output[13:0] led_year,
  output[13:0] led_hour,
  output[13:0] led_min,
  output[13:0] led_sec
);
endmodule
