/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module alarm(clk, rst_n, alarm_min, alarm_hour, alarm_i, minute, hour, alarm_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input [4:0] alarm_hour;
  wire [4:0] alarm_hour;
  input alarm_i;
  wire alarm_i;
  input [5:0] alarm_min;
  wire [5:0] alarm_min;
  output alarm_o;
  wire alarm_o;
  input clk;
  wire clk;
  input [4:0] hour;
  wire [4:0] hour;
  input [5:0] minute;
  wire [5:0] minute;
  input rst_n;
  wire rst_n;
  wire state_alarm;
  sky130_fd_sc_hd__xor2_2 _19_ (
    .A(state_alarm),
    .B(alarm_i),
    .X(_00_)
  );
  sky130_fd_sc_hd__xor2_2 _20_ (
    .A(hour[1]),
    .B(alarm_hour[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__or2_2 _21_ (
    .A(minute[3]),
    .B(alarm_min[3]),
    .X(_03_)
  );
  sky130_fd_sc_hd__nand2_2 _22_ (
    .A(minute[3]),
    .B(alarm_min[3]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_2 _23_ (
    .A(minute[5]),
    .B(alarm_min[5]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__or2_2 _24_ (
    .A(minute[5]),
    .B(alarm_min[5]),
    .X(_06_)
  );
  sky130_fd_sc_hd__a221o_2 _25_ (
    .A1(_03_),
    .A2(_04_),
    .B1(_05_),
    .B2(_06_),
    .C1(_02_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_2 _26_ (
    .A(minute[0]),
    .B(alarm_min[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__xor2_2 _27_ (
    .A(minute[2]),
    .B(alarm_min[2]),
    .X(_09_)
  );
  sky130_fd_sc_hd__xor2_2 _28_ (
    .A(hour[3]),
    .B(alarm_hour[3]),
    .X(_10_)
  );
  sky130_fd_sc_hd__xor2_2 _29_ (
    .A(hour[4]),
    .B(alarm_hour[4]),
    .X(_11_)
  );
  sky130_fd_sc_hd__or4_2 _30_ (
    .A(_08_),
    .B(_09_),
    .C(_10_),
    .D(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__xor2_2 _31_ (
    .A(hour[0]),
    .B(alarm_hour[0]),
    .X(_13_)
  );
  sky130_fd_sc_hd__xor2_2 _32_ (
    .A(hour[2]),
    .B(alarm_hour[2]),
    .X(_14_)
  );
  sky130_fd_sc_hd__xor2_2 _33_ (
    .A(minute[1]),
    .B(alarm_min[1]),
    .X(_15_)
  );
  sky130_fd_sc_hd__xor2_2 _34_ (
    .A(minute[4]),
    .B(alarm_min[4]),
    .X(_16_)
  );
  sky130_fd_sc_hd__or4_2 _35_ (
    .A(_13_),
    .B(_14_),
    .C(_15_),
    .D(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nor3_2 _36_ (
    .A(_07_),
    .B(_12_),
    .C(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o21a_2 _37_ (
    .A1(alarm_o),
    .A2(_18_),
    .B1(state_alarm),
    .X(_01_)
  );
  sky130_fd_sc_hd__dfrtp_2 _38_ (
    .CLK(clk),
    .D(_00_),
    .Q(state_alarm),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _39_ (
    .CLK(clk),
    .D(_01_),
    .Q(alarm_o),
    .RESET_B(rst_n)
  );
endmodule
