// Auto-generated by OpenLane
module decode_day(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input am_pm,
  input[6:0] year,
  input[3:0] month,
  output[4:0] day_num,
  output[4:0] hour_num
);
endmodule
